spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          # auto: create # 开发阶段使用
          auto: update
  flyway:
    enabled: false # 启用或禁用 flyway


starcoin:
  sender-address: "0x569AB535990a17Ac9Afd1bc57Faec683"
  sender-public-key: "0x122b7632cf4aab6f0fc3e462db3601ecd3234d9567c8deac2808f5cda26add36"
  chain-id: 254
  # ----------------------------------
  event-filter:
    from-address: "0x569AB535990a17Ac9Afd1bc57Faec683"
    cross-chain-deposit-event-type-tag: "0x569AB535990a17Ac9Afd1bc57Faec683::Bifrost::CrossChainDepositEvent"
  # ----------------------------------
  needed-block-confirmations: 1


ethereum:
  # websocket-service-url: wss://mainnet.infura.io/ws/v3/72637bfa15a940dcadcec25a6fe0fca1
  # ----------------------------------
  # ropsten config:
  websocket-service-url: wss://ropsten.infura.io/ws/v3/72637bfa15a940dcadcec25a6fe0fca1
  http-service-url: https://ropsten.infura.io/v3/72637bfa15a940dcadcec25a6fe0fca1
  chain-id: 3 # ropsten
  mint-stc-contract-address: "0xF21aF28b798E40B1b8734655C3662B360367914e"
  sender-address: "0x71DFDD2BF49E8Af5226E0078efA31ecf258bC44E"
  sender-private-key: "0xc9f5f173242c5323493c0595dd73be4bda87ab2d90b8ed4b9c047352562ff3b0"
  # ----------------------------------
  # local ganache config:
  # http-service-url: HTTP://127.0.0.1:7545
  # chain-id: 1337
  # mint-stc-contract-address: "0x3d8c97DF6A0948f11273b0367579B1f0413DE0C4"
  # sender-address: "0x414d6e7B82E9Ce949d468d502057483195C69df9"
  # sender-private-key: "bc4f359cd7a64bca074ffdeafcd18e3c2a860f22c64611577fcb5108fec850da"
  # ----------------------------------
  # ethereum transaction
  transaction-resend-task-service:
    fixed-delay: 10000
    resend-created-before-seconds: 5
  transaction-confirm-task-service:
    fixed-delay: 10000
    confirm-Transaction-created-before-seconds: 5
  # ----------------------------------
  # form ethereum...
  withdraw-log-filter-address: "0xF21aF28b798E40B1b8734655C3662B360367914e"
  # ----------------------------------
  needed-block-confirmations: 1


token-price-service:
  base-url: http://k8s-default-starcoin-cbf39ae390-308376289.ap-northeast-1.elb.amazonaws.com/barnard


logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
      starcoin:
        bifrost: DEBUG
      # 输出数据库模型（开发阶段）
      hibernate:
        tool:
          hbm2ddl: DEBUG

